### PR TITLE
Bindings

### PR DESCRIPTION
**Pull request by jobtg**
Some bindings for primitive values (still boxed)

### CODE REVIEW

**Comment by danieldk** [comment]
Looks good to me... In the unit tests, I'd also add some negative numbers to assure that the sign bit is correctly preserved.

Also, if Bytes.java is from HBase verbatim, there should be copyright headers ;).

**Comment by jobtg** [comment]
Copyright headers added & added some negative number tests.

**Comment by danieldk** [comment]
Looks good!

**Comment by nielsslot** [comment]
Job: You don't want to change the copyright headers of the other files to be explicitly Apache 2 license? (Like the rest of the code). So that they are copyright GridLine, but licensed as Apache 2.

**Comment by jobtg** [comment]
Sure, done.

**Comment by danieldk** [comment]
One more thing :). HBase has a NOTICE file:

http://svn.apache.org/viewvc/hbase/trunk/NOTICE.txt?view=markup&pathrev=1405073

So, the NOTICE file in leveldb-mapapi should contain:

```
This product includes software developed by The Apache Software
Foundation (http://www.apache.org/).
```

**Pull request merged**
